# Custom Language File for Launcher Customizer

[ejs.app]
title = "ArkaniaZ Launcher"

[ejs.landing]
mediaGitHubURL = "https://arkaniaz.fr/"
mediaTwitterURL = "#"
mediaInstagramURL = "https://www.tiktok.com/@arkingstudio_officiel"
mediaYouTubeURL = "https://www.youtube.com/@pierrre224"
mediaDiscordURL = "https://discordapp.com/invite/PYWJw99DNf"

[ejs.settings]
sourceGithubLink = "https://github.com/Creat789/ArkaniaZLauncher"
supportLink = "https://github.com/Creat789/ArkaniaZLauncher/issues"

[ejs.welcome]
welcomeHeader = "WELCOME TO ARKANIAZ"
welcomeDescription = ""
